add xargs delimiter logic

diff --git a/cleanup-tool b/cleanup-tool
--- a/cleanup-tool
+++ b/cleanup-tool
@@ -23,28 +23,32 @@ delete_archives() {
     # already existing in the backup folder displaying history of all backed up archives
     archive_log_file="$user_archive_folder/archive-logs-history.log"
 
-    # deleting logs
-    echo -e "🚮 Deleting old archives, please wait..."
-    # fetching timestamp
-    local timestamp=$(date +%Y%m%d_%H%M%S)
-    # delete all archives (tar.gz) in user_archive_folder older than 3 days
-    find "$user_archive_folder" -type f -name "*.tar.gz" -mtime +3 -exec rm {} \;
-    # saving current tar exit code after compression
-    find_exit_code=$?
+    # placing files to delete in a variable
+    tarfiles_to_delete=$(find "$user_archive_folder" -type f -name "*.tar.gz" -mmin +3)
 
-    # error checking
-    # if deleted successfully...
-    if [[ $find_exit_code -eq 0 ]]; then
+    # if there are files older than 3 days delete then else echo no files found older than 3 days
+    if [[ -n "$tarfiles_to_delete" ]]; then
+        echo -e "🚮 Deleting old archives, please wait..."
         # creating if doesn't exist, archive log file in /var/backups/my-logs-backup-folder
         touch "$archive_log_file"
-        echo "✅ Sucess: Old archives deleted"
         # updating archive log file of the new compression process
-        echo "🚮 Cleanup Sucess: [$timestamp]: Backups older than 3 days deleted!" >> "$archive_log_file"
+        echo -e "Here is the list of tar files being deleted:\n$tarfiles_to_delete" >> "$archive_log_file"
+        # delete all archives (tar.gz) in user_archive_folder older than 3 days
+        find "$user_archive_folder" -type f -name "*.tar.gz" -mmin +3 -print0 | xargs -0 rm
+        echo "✅ Sucess: Old archives deleted"
+        echo "🚮 Cleanup Sucess: [$(date +%Y%m%d_%H%M%S)]: Backups older than 3 days deleted!" >> "$archive_log_file"
     else
-        echo "❌ Cleanup failed with exit code $find_exit_code"
+        echo "No files older than 3 days found."
+    fi
+
+    # error checking
+    if [[ $? -ne 0 ]]; then
+        echo "❌ Cleanup failed with exit code $?"
         return 1
     fi
 }
 
 # running function with folder passed arg in terminal
 delete_archives "$1"
+
+# learn about xargs
